# Integration with travis-ci

language: r
sudo: required

env: NOT_CRAN="true"

r_binary_packages:
  - testthat
  - knitr
  - ggplot2
  - scales
  - rpart
  - tree
  - cluster

branches:
  only:
    - master
    - release
    - dev
    
notifications:
  email:
    on_success: change
    on_failure: change